# 10.4、defer错误关闭文件
> 程序在批量循环处理文件时，可能在循环中定义一个`defer`来关闭文件，但defer是在函数结束时才调用，也就是说文件并没有及时关闭。

```go
package main
import (
	"fmt"
	"os"
	"io/ioutil"
)
func main(){
	var files = []string{"a.txt","b.txt"}
	
	//错误用法
	for _,file := range files {
		var fd *os.File
		var err error
		if fd ,err = os.Open(file);err != nil {
			fmt.Println("opend file error:",err)
		}
		defer fd.Close() //本次循环结束文件并未关闭,应同步关闭或者使用函数关闭
		content,err := ioutil.ReadAll(fd)
		fmt.Println(content)
	} 
}

//正确用法
func true1(){
		var files = []string{"a.txt","b.txt"}
    	
    	//错误用法
    	for _,file := range files {
    		var fd *os.File
    		var err error
    		if fd ,err = os.Open(file);err != nil {
    			fmt.Println("opend file error:",err)
    		}
    		content,_ := ioutil.ReadAll(fd)
    		fd.Close() //同步关闭
    		fmt.Println(content)
    	} 
}

func true2(){
	var files = []string{"a.txt","b.txt"}
    	
    	//错误用法
    	for _,file := range files {
    		var fd *os.File
    		var err error
    		if fd ,err = os.Open(file);err != nil {
    			fmt.Println("opend file error:",err)
    		}
    		func(fd *os.File){
    		   defer fd.Close() //使用函数关闭	
    	       content,_ := ioutil.ReadAll(fd)
    	       fmt.Println(content)
    		}(fd)

    	} 
}
```